### ISSUE TITLE
Mods Do Not Load

### ISSUE THREAD

**Issue by JEB12345** [frantjc/sindri#48]
Hello,

I have been running valheimw for a few weeks now and it runs well as a vanilla server. I recently tried to load some server side mods, but it seems that none of the mods load. I am able to see the system pull the mods listed in my compose.yaml file and put them into the BepInEx plugins folder. However, the image doesn't seem to load the mods (and possibly BepInEx) when I start it up.

Below is my compose.yaml file:
```
services:
  valheimw:
    image: ghcr.io/frantjc/valheimw
    command:
      # The name of the Valheim server's save files.
      # If they already exist, it will load them. If
      # they do not, it will create them.
      # Optional. Default "sindri".

[log.txt](https://github.com/user-attachments/files/18834780/log.txt)

      # - --world=hello
      # The name of the Valheim server as a player would
      # see it in-game when connecting to it.
      # Optional. Default "sindri".
      # - --name=there
      # Can be specified if you want to run a
      # pre-release version of the Valheim server.
      # Optional.
      # - --beta=public-test
      # - --beta-password=yesimadebackups
      # Browse https://valheim.thunderstore.io/ for available mods.
      # Names are case-sensitive.
      # Optional.
      - --mod=SpikeHimself/XPortal
      - --mod=ValheimModding/Jotunn
      - --save-interval=15m
    environment:
      # The password you will use to connect to your server.
      # Required. Must be at least 5 characters, and cannot
      # be contained within your world name. Default world name
      # is "sindri".
      VALHEIM_PASSWORD: test
    volumes:
      # `valheimw` caches stuff here and the Valheim server's
      # save data is here by default.
      - ./saves:/home/valheimw/.cache
    ports:
      # Expose the Valheim server's port.
      # If you change the Valheim server's port from its default,
      # via `--port`, ensure that this is changed to match.
      - 2456:2456/udp
      - 8080:8080
networks: {}
```

I also uploaded a log file with the terminal output from starting the docker compose.

[log.txt](https://github.com/user-attachments/files/18834786/log.txt)

**Comment by frantjc** [comment]
Hi @JEB12345, thanks for raising an issue!

I looked into this and found a potential bug that could have caused this behavior. It's quite the process to test it myself, so I just released a new version, v3.1.1, in hopes that you could try it out and let me know the results.

**Comment by JEB12345** [comment]
I pulled the latest build, but it didn't seem to solve the issue. I now get this error on the output:

```
valheim-valheimw-1  | ERROR: ld.so: object '/home/valheimw/.cache/sindri/valheimw/doorstop_libs/libdoorstop_x86.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
valheim-valheimw-1  | [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
valheim-valheimw-1  | CAppInfoCacheReadFromDiskThread took 68 milliseconds to initialize
valheim-valheimw-1  | Setting breakpad minidump AppID = 892970
valheim-valheimw-1  | SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
valheim-valheimw-1  | [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
valheim-valheimw-1  | src/clientdll/cminterface.cpp (2124) : !BLoggedOn()
```

Here is the terminal output from this test as well.

[log.txt](https://github.com/user-attachments/files/18837164/log.txt)

**Comment by frantjc** [comment]
@JEB12345 This is looking much more promising:

```
valheimw-1  | [Message:   BepInEx] BepInEx 5.4.22.0 - valheim_server (02/17/2025 21:59:25)
valheimw-1  | [Message:   BepInEx] User is running BepInExPack Valheim version 5.4.2200 from Thunderstore
valheimw-1  | [Info   :   BepInEx] Running under Unity vUnknown (post-2017)
valheimw-1  | [Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
valheimw-1  | [Info   :   BepInEx] Supports SRE: True
valheimw-1  | [Info   :   BepInEx] System platform: Bits64, Linux
valheimw-1  | [Message:   BepInEx] Preloader started
valheimw-1  | [Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
valheimw-1  | [Info   :   BepInEx] 1 patcher plugin loaded
valheimw-1  | [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
valheimw-1  | [Message:   BepInEx] Preloader finished
valheimw-1  | [Info   :   BepInEx] Detected Unity version: v2022.3.50f1
valheimw-1  | [Message:   BepInEx] Chainloader ready
valheimw-1  | [Message:   BepInEx] Chainloader started
valheimw-1  | [Info   :   BepInEx] 3 plugins to load
valheimw-1  | [Info   :   BepInEx] Loading [Jotunn 2.20.0]
valheimw-1  | [Info   :Jotunn.Main] Initializing ModCompatibility
```
```
valheimw-1  | [Info   :   BepInEx] Loading [XPortal 1.2.21]
valheimw-1  | [Info   :Jotunn.Main] Initializing GUIManager
valheimw-1  | [Info   :Jotunn.Main] Initializing MinimapManager
```

There's a ton of not-so-happy looking logs, too, but I have to assume that those are expected with these mods and not to do with `valheimw`.

Let me know if v3.1.2 works for you.

**Comment by JEB12345** [comment]
@frantjc Thanks for all this work! It seems that the mods get loaded now. 

However, there is a miss match of the mod versions between the server and client side. My suspicion is that the Jotunn mod version only works with particular versions of Valhiem (in particular the network version is different between the server and the latest game update). This may be why the Jotunn version on the docker image isn't the latest version available. When I manually downgraded my version of Jotunn to the one loaded automatically by the docker image (v2.23.2 -> v2.20.2), it breaks my client's valhiem game by messing with the game's start screen.

**This really isn't a core sindri/valheimw issue anymore, so if you want to close the issue I'm ok with that.** 

Attached are some screenshots of the current issues I am having and some output logs from valheimw and BepInEx.

![Image](https://github.com/user-attachments/assets/3005f604-d6cf-4f74-89fb-2a7353aff7a5)
Jotunn seems to have a nice version/error checker when you connect to a server

![Image](https://github.com/user-attachments/assets/1946b9fe-1c03-48ba-8aa3-b8a8b38a707d)
This is with my current game version, Jotunn v2.20.2 and XPortal 1.2.21 breaking my loading screen

[BepInEx_LogOutput_client.log](https://github.com/user-attachments/files/18854724/BepInEx_LogOutput_client.log)
[BepInEx_LogOutput_server.log](https://github.com/user-attachments/files/18854722/BepInEx_LogOutput_server.log)
[valheimw_log_noMods.txt](https://github.com/user-attachments/files/18854725/valheimw_log_noMods.txt)
[valheimw_log.txt](https://github.com/user-attachments/files/18854723/valheimw_log.txt)

**Comment by frantjc** [comment]
@JEB12345 If I understand correctly, the problem here is that [XPortal says that it wants version 2.20.0 of Jotunn](https://thunderstore.io/c/valheim/p/SpikeHimself/XPortal/), but you need to override it with a newer version.

If yes, I do want to support this.

**Comment by JEB12345** [comment]
@frantjc That did it! The XPortal mod now works!! 😄
